<?php

class fileuploader implements vcl_interface
{
	public function __construct()
	{
		require_once AW_DIR . "addons/Solmetra/fileuploader/SolmetraUploader.php";
	}

	/**
		@attrib api=1 params=name
		@param name type=string
			Component identifier
		@param folder type=string default=
			Folder where uploaded file is saved, default is under current site files folder autogenerated path
		@comment
		@returns string
			File uploader component
		@errors
	**/
	public function create($arr)
	{
		$fileuploader = "";
		$solmetraUploader = new SolmetraUploader(
			aw_ini_get("vcl.fileuploader.upload_folder"),           // a base path to Flash Uploader's directory (relative to the page)
			'upload.php',       // path to a file that handles file uploads (relative to uploader.swf) [optional]
			'../config.php'  // path to a server-side config file (relative to the page) [optional]
		);
		return $fileuploader;
	}

	public function init_vcl_property($arr)
	{
		$prop = $arr["property"];
		$name = $prop["name"];
		$prop["value"] = (isset($prop["value"]) and is_int($prop["value"])) ? $prop["value"] : $arr["obj_inst"]->prop($name);
		$prop["value"] = $this->create($prop);
		return array($name => $prop);
	}

	public function process_vcl_property(&$arr)
	{
	}
}
